src/validator.hpp:10:14: error
'void Validator::addRule(T, auto:1) [with T = main()::<lambda(auto:2)>; auto:1 = bool]', declared using local type 'main()::<lambda(auto:2)>', is used but never defined [-fpermissive]
         void addRule(T rule, auto value);
              ^~~~~~~